import ReviewIconOne from "../assets/HomePageImages/CourseDetailSectionImages/ReviewIconOne.png";
import ReviewIconTwo from "../assets/HomePageImages/CourseDetailSectionImages/ReviewIconTwo.png";
import ReviewIconThree from "../assets/HomePageImages/CourseDetailSectionImages/ReviewIconThree.png";
import ReviewIconFour from "../assets/HomePageImages/CourseDetailSectionImages/ReviewIconFour.png";

import TestimonialImageOne from "../assets/HomePageImages/TestimonialSectionImages/TestimonialImageOne.png";
import TestimonialImageTwo from "../assets/HomePageImages/TestimonialSectionImages/TestimonialImageTwo.png";
import TestimonialImageThree from "../assets/HomePageImages/TestimonialSectionImages/TestimonialImageThree.png";

const FeatureCourseData = [
  {
    id: 1,
    title: "Learn Figma from Basic",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 2,
    title: "Build Digital Asset",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 3,
    title: "the Power of Big Data",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 4,
    title: "Learn Python Programming",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$27",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1587620962725-abab7fe55159?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 5,
    title: "Build Digital Asset",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$15",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1619410283995-43d9134e7656?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 6,
    title: "the Power of Big Data",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$23",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
];

const FeatureCategories = [
  "Featured",
  "Music",
  "Drawing & Painting",
  "Marketing",
  "Animation",
  "Social Media",
  "UI/UX Design",
  "Creative Marketing",
  "Digital Illustration",
  "Film & Video",
  "Crafts",
  "Freelance & Entrepreneurship",
  "Graphic Design",
  "Photography",
  "Productivity",
  "Web Development",
  "Data Science",
  "Cooking",
  "+ More",
];

const ALL_COURSES = [
  {
    id: 1,
    title: "Learn Figma from Basic",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    category: "UI/UX Design",
    image:
      "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 2,
    title: "Build Digital Asset",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    category: "Featured",
    image:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 3,
    title: "the Power of Big Data",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    category: "Marketing",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 4,
    title: "Balancing Productivity an...",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    category: "Featured",
    image:
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 5,
    title: "Mastering Money Manage...",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    category: "Marketing",
    image:
      "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 6,
    title: "From Idea to Startup Succ...",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    category: "Creative Marketing",
    image:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 7,
    title: "Digital Illustration Workshop",
    author: "purepearl studio",
    rating: 4.8,
    lessons: "20 Lessons",
    duration: "3 hours 10m",
    comments: "84 Comments",
    level: "Intermediate",
    price: "$35",
    priceType: "/lifetime",
    category: "Drawing & Painting",
    image:
      "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80",
    studentsCount: "42+",
  },
  {
    id: 8,
    title: "Advanced React & Web Dev",
    author: "purepearl studio",
    rating: 4.9,
    lessons: "25 Lessons",
    duration: "5 hours 40m",
    comments: "120 Comments",
    level: "Advanced",
    price: "$49",
    priceType: "/lifetime",
    category: "UI/UX Design",
    image:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80",
    studentsCount: "100+",
  },
  {
    id: 9,
    title: "Music Production Masterclass",
    author: "purepearl studio",
    rating: 4.7,
    lessons: "15 Lessons",
    duration: "4 hours 00m",
    comments: "45 Comments",
    level: "Beginner",
    price: "$30",
    priceType: "/lifetime",
    category: "Music",
    image:
      "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80",
    studentsCount: "18+",
  },
  {
    id: 10,
    title: "Social Media Strategy 2026",
    author: "purepearl studio",
    rating: 4.6,
    lessons: "12 Lessons",
    duration: "1 hour 45m",
    comments: "38 Comments",
    level: "Beginner",
    price: "$20",
    priceType: "/lifetime",
    category: "Social Media",
    image:
      "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=800&q=80",
    studentsCount: "50+",
  },
  {
    id: 11,
    title: "Culinary Arts & Cooking",
    author: "purepearl studio",
    rating: 4.9,
    lessons: "18 Lessons",
    duration: "3 hours 30m",
    comments: "62 Comments",
    level: "Beginner",
    price: "$28",
    priceType: "/lifetime",
    category: "Cooking",
    image:
      "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80",
    studentsCount: "33+",
  },
  {
    id: 12,
    title: "3D Animation Essentials",
    author: "purepearl studio",
    rating: 4.8,
    lessons: "22 Lessons",
    duration: "4 hours 50m",
    comments: "91 Comments",
    level: "Intermediate",
    price: "$40",
    priceType: "/lifetime",
    category: "Animation",
    image:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    studentsCount: "64+",
  },
  {
    id: 13,
    title: "Python for Data Science & ML",
    author: "purepearl studio",
    rating: 4.9,
    lessons: "30 Lessons",
    duration: "6 hours 15m",
    comments: "142 Comments",
    level: "Intermediate",
    price: "$45",
    priceType: "/lifetime",
    category: "Data Science",
    image:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    studentsCount: "115+",
  },
  {
    id: 14,
    title: "Brand Identity & Logo Design",
    author: "purepearl studio",
    rating: 4.7,
    lessons: "16 Lessons",
    duration: "2 hours 45m",
    comments: "51 Comments",
    level: "Beginner",
    price: "$29",
    priceType: "/lifetime",
    category: "UI/UX Design",
    image:
      "https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=800&q=80",
    studentsCount: "38+",
  },
  {
    id: 15,
    title: "SEO Mastery for Small Business",
    author: "purepearl studio",
    rating: 4.6,
    lessons: "14 Lessons",
    duration: "2 hours 10m",
    comments: "33 Comments",
    level: "Beginner",
    price: "$22",
    priceType: "/lifetime",
    category: "Marketing",
    image:
      "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=800&q=80",
    studentsCount: "47+",
  },
  {
    id: 16,
    title: "Mobile App Design with Flutter",
    author: "purepearl studio",
    rating: 4.8,
    lessons: "24 Lessons",
    duration: "5 hours 00m",
    comments: "78 Comments",
    level: "Intermediate",
    price: "$42",
    priceType: "/lifetime",
    category: "Featured",
    image:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80",
    studentsCount: "82+",
  },
  {
    id: 17,
    title: "Commercial Photography 101",
    author: "purepearl studio",
    rating: 4.8,
    lessons: "19 Lessons",
    duration: "3 hours 20m",
    comments: "67 Comments",
    level: "Beginner",
    price: "$32",
    priceType: "/lifetime",
    category: "Drawing & Painting",
    image:
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
    studentsCount: "53+",
  },
  {
    id: 18,
    title: "Cybersecurity Fundamentals",
    author: "purepearl studio",
    rating: 4.9,
    lessons: "21 Lessons",
    duration: "4 hours 15m",
    comments: "95 Comments",
    level: "Intermediate",
    price: "$38",
    priceType: "/lifetime",
    category: "Featured",
    image:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
    studentsCount: "90+",
  },
  {
    id: 19,
    title: "Video Editing with Premiere Pro",
    author: "purepearl studio",
    rating: 4.7,
    lessons: "18 Lessons",
    duration: "3 hours 45m",
    comments: "58 Comments",
    level: "Beginner",
    price: "$27",
    priceType: "/lifetime",
    category: "Animation",
    image:
      "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=800&q=80",
    studentsCount: "41+",
  },
  {
    id: 20,
    title: "Acoustic Guitar for Beginners",
    author: "purepearl studio",
    rating: 4.9,
    lessons: "15 Lessons",
    duration: "2 hours 50m",
    comments: "72 Comments",
    level: "Beginner",
    price: "$24",
    priceType: "/lifetime",
    category: "Music",
    image:
      "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=800&q=80",
    studentsCount: "66+",
  },
  {
    id: 21,
    title: "Copywriting & Content Strategy",
    author: "purepearl studio",
    rating: 4.6,
    lessons: "13 Lessons",
    duration: "1 hour 55m",
    comments: "29 Comments",
    level: "Beginner",
    price: "$19",
    priceType: "/lifetime",
    category: "Creative Marketing",
    image:
      "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80",
    studentsCount: "31+",
  },
  {
    id: 22,
    title: "Full-Stack Node.js & MongoDB",
    author: "purepearl studio",
    rating: 4.9,
    lessons: "28 Lessons",
    duration: "6 hours 00m",
    comments: "110 Comments",
    level: "Advanced",
    price: "$50",
    priceType: "/lifetime",
    category: "UI/UX Design",
    image:
      "https://images.unsplash.com/photo-1627398242454-45a1465c2479?auto=format&fit=crop&w=800&q=80",
    studentsCount: "128+",
  },
  {
    id: 23,
    title: "Art of Public Speaking",
    author: "purepearl studio",
    rating: 4.8,
    lessons: "11 Lessons",
    duration: "1 hour 30m",
    comments: "44 Comments",
    level: "Beginner",
    price: "$21",
    priceType: "/lifetime",
    category: "Social Media",
    image:
      "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80",
    studentsCount: "39+",
  },
  {
    id: 24,
    title: "Pastry & Baking Masterclass",
    author: "purepearl studio",
    rating: 4.9,
    lessons: "16 Lessons",
    duration: "3 hours 15m",
    comments: "81 Comments",
    level: "Intermediate",
    price: "$32",
    priceType: "/lifetime",
    category: "Cooking",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    studentsCount: "58+",
  },
];

const CreatorCourses = [
  {
    id: 1,
    title: "Learn Figma from Basic",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 2,
    title: "Build Digital Asset",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 3,
    title: "the Power of Big Data",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 4,
    title: "Balancing Productivity an...",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 5,
    title: "Mastering Money Manage...",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
  {
    id: 6,
    title: "From Idea to Startup Succ...",
    author: "purepearl studio",
    rating: 4.5,
    lessons: "17 Lessons",
    duration: "2 hours 16m",
    comments: "59 Comments",
    level: "Beginner",
    price: "$25",
    priceType: "/lifetime",
    image:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80",
    studentsCount: "26+",
  },
];

const ReviewData = [
  {
    name: "PurePearl Studio",
    role: "UI/UX Designer",
    time: "a year ago",
    quote:
      '"The course provided me with a comprehensive understanding of digital asset creation. The lessons were in-depth, practical, and immediately applicable to my work. Highly recommended!"',
    avatar: ReviewIconOne,
  },
  {
    name: "Albert Flores",
    role: "UI/UX Designer",
    time: "a year ago",
    quote:
      '"This course transformed my approach to digital design. The combination of theory, hands-on exercises, and real-world applications made it a truly enriching experience. Excited to implement what I\'ve learned!"',
    avatar: ReviewIconTwo,
  },
  {
    name: "Cody Fisher",
    role: "UI/UX Designer",
    time: "a year ago",
    quote:
      '"The project showcase and critique module created a collaborative environment where I could showcase my work, receive valuable feedback, and refine my skills. It added a unique and valuable dimension to the learning process."',
    avatar: ReviewIconThree,
  },
  {
    name: "Brooklyn Simmons",
    role: "UI/UX Designer",
    time: "a year ago",
    quote:
      '"The lessons on optimizing digital assets for various platforms were particularly insightful. The course adapts to the evolving digital landscape, and the engaging content kept me motivated throughout."',
    avatar: ReviewIconFour,
  },
];

const TestimonialsData = [
  {
    id: 1,
    name: "Sarah M.",
    role: "Enthusiastic Learner",
    avatar: TestimonialImageOne,
    quote:
      '"ByteSpace has transformed my approach to learning. The diverse range of courses and the quality of content provided by creators have exceeded my expectations. The platform truly fosters a sense of community and lifelong learning."',
  },
  {
    id: 2,
    name: "James L.",
    role: "Lifelong Learner",
    avatar: TestimonialImageTwo,
    quote:
      '"I\'ve tried several online learning platforms, and ByteSpace stands out for its vibrant community and the variety of courses available. The easy navigation and engaging content make it a go-to platform for continuous skill development."',
  },
  {
    id: 3,
    name: "Alex B.",
    role: "Inspired Creator",
    avatar: TestimonialImageThree,
    quote:
      '"As a creator, ByteSpace has been a game-changer for me. The Course Editor is user-friendly, and the support from the community is incredible. It\'s fulfilling to see my courses making a positive impact on learners globally."',
  },
];

const position = "top-right";
const toastOptions = {
  duration: 3000,
  style: {
    background: "#1052FE",
    color: "#ffffff",
    border: "1px solid rgba(203, 255, 0, 0.4)",
    borderRadius: "16px",
    padding: "12px 20px",
    fontSize: "14px",
    fontWeight: "600",
    boxShadow: "0 20px 25px -5px rgba(16, 82, 254, 0.3)",
  },
  success: {
    iconTheme: {
      primary: "#CBFF00", // Lime green success icon
      secondary: "#1052FE",
    },
  },
  error: {
    iconTheme: {
      primary: "#FF4D4D",
      secondary: "#ffffff",
    },
  },
};

export {
  ALL_COURSES,
  FeatureCourseData,
  FeatureCategories,
  CreatorCourses,
  TestimonialsData,
  ReviewData,
  position,
  toastOptions,
};
